package io.github.g4lb.autor3search.config;

import java.util.List;

/**
 * Renders a {@link Config} as YAML with an explanatory comment above every
 * field, so a human opening the file for the first time understands each knob
 * without leaving it. {@code init} writes this once (or with {@code -force});
 * comments are not preserved by any later automated write, because there is no
 * later automated write.
 */
public final class ConfigRenderer {
    private ConfigRenderer() {}

    public static String render(Config cfg) {
        StringBuilder b = new StringBuilder();
        b.append("# autor3search-java run configuration.\n");
        b.append("# Generated by `autor3search-java init`. Safe to hand-edit — but only BEFORE\n");
        b.append("# `autor3search-java baseline`: this file is hashed at baseline time and any\n");
        b.append("# change during a run fails every later eval with reason config_changed.\n\n");

        b.append("# Benchmarks declares exactly which JMH benchmark methods count toward the\n");
        b.append("# score, as fully qualified <package>.<Class>.<method> names. init discovered\n");
        b.append("# these by scanning for @Benchmark; edit the list by hand to narrow or widen\n");
        b.append("# what is measured. Empty means every discovered benchmark.\n");
        list(b, "benchmarks", cfg.benchmarks);
        b.append('\n');

        b.append("# Scope lists the repository path patterns the agent is allowed to edit.\n");
        b.append("# A trailing \"/...\" means the directory and everything under it, so\n");
        b.append("# \"./...\" is the whole repository and \"./src/main/java/...\" is that tree;\n");
        b.append("# without it, \"./src/main/java/com/example\" matches that one directory's own\n");
        b.append("# files and not its subdirectories. Anything outside these patterns is\n");
        b.append("# rejected by the scope gate before it is built.\n");
        list(b, "scope", cfg.scope);
        b.append('\n');

        b.append("# Count is the number of interleaved A/B measurement rounds per side. One\n");
        b.append("# round is one complete JMH invocation, whose reported score becomes a single\n");
        b.append("# observation. Higher counts are slower but more resistant to noise. 4 is the\n");
        b.append("# hard floor: below it the significance test can never report p < 0.05, so\n");
        b.append("# every experiment would be discarded no matter how large the real\n");
        b.append("# improvement is. The default of 10 leaves real margin.\n");
        b.append("count: ").append(cfg.count).append("\n\n");

        b.append("# Forks is JMH's -f: how many fresh JVMs each round measures in. 1 is the\n");
        b.append("# right default here because the interleaving already provides the\n");
        b.append("# between-JVM variation that -f normally exists to capture, and every extra\n");
        b.append("# fork multiplies the wall time of an already long round.\n");
        b.append("forks: ").append(cfg.forks).append("\n\n");

        b.append("# Warmup and measurement iterations per fork (JMH's -wi and -i). Warmup\n");
        b.append("# iterations are discarded; the mean of the measurement iterations is the\n");
        b.append("# round's observation. Java needs the warmup: a JVM measured cold reports\n");
        b.append("# interpreter and C1 timings rather than the steady-state speed of the code\n");
        b.append("# being compared, and the two candidates would not even be on the same\n");
        b.append("# compilation tier.\n");
        b.append("warmup_iterations: ").append(cfg.warmupIterations).append('\n');
        b.append("measurement_iterations: ").append(cfg.measurementIterations).append("\n\n");

        b.append("# Benchtime is how long each warmup and measurement iteration runs (JMH's -w\n");
        b.append("# and -r). It must be a duration (e.g. 1s, 200ms) — a fixed iteration count is\n");
        b.append("# deliberately not accepted, because a candidate that is twice as fast would\n");
        b.append("# then finish in half the wall time and be measured under different thermal\n");
        b.append("# conditions, which is exactly what the interleaved A/B design exists to\n");
        b.append("# eliminate.\n");
        b.append("benchtime: ").append(cfg.benchtime).append("\n\n");

        b.append("# JvmArgs is passed to JMH's -jvmArgs for the forked benchmark JVMs. Use it to\n");
        b.append("# pin the heap (-Xmx2g -Xms2g) or the GC, both of which cut measurement\n");
        b.append("# variance considerably. Whatever you put here applies identically to the\n");
        b.append("# baseline and the candidate, so it changes what is measured, never who wins.\n");
        list(b, "jvm_args", cfg.jvmArgs);
        b.append('\n');

        b.append("# MaxRegressPct is the largest tolerated statistically significant regression,\n");
        b.append("# as a percentage. Any benchmark that regresses more than this rejects the\n");
        b.append("# whole experiment, however good the overall score.\n");
        b.append("max_regress_pct: ").append(num(cfg.maxRegressPct)).append("\n\n");

        b.append("# MinEffectPct is the smallest geomean improvement, as a percentage, that KEEP\n");
        b.append("# will accept — the score must fall below 1 - min_effect_pct/100, not merely\n");
        b.append("# below 1. A change can be statistically significant and still be too small to\n");
        b.append("# be worth a commit in an unattended overnight loop; this is the knob that\n");
        b.append("# says how small is too small. Lowering it banks smaller real wins but also\n");
        b.append("# more measurement noise, since any fixed significance threshold admits some\n");
        b.append("# false positives. Raise it on a noisy machine.\n");
        b.append("min_effect_pct: ").append(num(cfg.minEffectPct)).append("\n\n");

        b.append("# Timeout bounds each subprocess phase: the compile, the test run, and each\n");
        b.append("# individual measurement round. A round is forks x (warmup + measurement)\n");
        b.append("# iterations of benchtime each, per benchmark, so this needs real headroom.\n");
        b.append("timeout: ").append(cfg.timeout).append("\n\n");

        b.append("# Unfreeze lists test sources deliberately exempted from the baseline freeze —\n");
        b.append("# normally empty. Only add a file here if you specifically want the agent to\n");
        b.append("# be able to edit it, understanding that this weakens the guarantee that the\n");
        b.append("# success criteria cannot be gamed.\n");
        list(b, "unfreeze", cfg.unfreeze);
        b.append('\n');

        b.append("# BuildTool selects how the repository is compiled, tested and put on a\n");
        b.append("# classpath: auto (detect from pom.xml / build.gradle), maven, or gradle.\n");
        b.append("build_tool: ").append(cfg.buildTool).append('\n');

        return b.toString();
    }

    /** Renders a YAML block sequence, or "key: []" when the list is empty. */
    private static void list(StringBuilder b, String key, List<String> items) {
        if (items == null || items.isEmpty()) {
            b.append(key).append(": []\n");
            return;
        }
        b.append(key).append(":\n");
        for (String item : items) {
            b.append("  - ").append(item).append('\n');
        }
    }

    /** Renders a double without a trailing ".0" on a whole number. */
    private static String num(double d) {
        if (d == Math.rint(d) && !Double.isInfinite(d)) {
            return String.valueOf((long) d);
        }
        return String.valueOf(d);
    }
}
